name: Python application with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Run Docker container for testing
      run: docker run --name flask-container -d -p 4000:4000 flask-app

    - name: Test Docker container
      run: |
        docker exec flask-container curl -f http://localhost:4000 || (echo "Application is not responding!" && exit 1)

    - name: Stop and remove Docker container
      run: |
        docker stop flask-container
        docker rm flask-container

  build-and-publish:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-calculator .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./DockerFile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flasktest-app:latest
  
    - name: Image digest
      run: echo ${{ steps.build-and-publish.outputs.digest }}
